apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
