replicaCount: 1

image:
  repository: nelonissle7/gpt_chat
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8003

env:
  - name: OLLAMA_MODEL
    value: "llama3"
  - name: OLLAMA_API_URL
    value: "http://ollama:11434"
  - name: MONGO_INITDB_ROOT_USERNAME
    value: "mongoadmin"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: chat-service-secrets
        key: SECRET_KEY
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: chat-service-secrets
        key: MONGO_INITDB_ROOT_PASSWORD

resources: {}

secrets:
  SECRET_KEY: ""
  MONGO_INITDB_ROOT_PASSWORD: ""

logsPersistence:
  enabled: true
  size: 10Gi