# Default values for elasticsearch
nameOverride: ""
fullnameOverride: ""

# Namespace to deploy resources
namespace: gpt-monitoring

# Replicas for elasticsearch cluster
replicaCount: 1

# Pod resources
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Image configuration
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.6.0"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 9200
  targetPort: 9200

# Persistence configuration
persistence:
  enabled: true
  storageClass: "standard"
  size: "30Gi"
  accessMode: ReadWriteOnce

# Elasticsearch configuration
config:
  discoveryType: "single-node"
  javaOpts: "-Xms1g -Xmx1g"
  xpackSecurityEnabled: "false"
  clusterName: "gpt-elasticsearch"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: elasticsearch.gpt-backend.local
      paths:
        - path: /
          pathType: Prefix