replicaCount: 1

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

env: []
  # - name: MONGO_INITDB_ROOT_USERNAME
  #   value: "root"
  # - name: MONGO_INITDB_ROOT_PASSWORD
  #   value: "example"

resources: {}