apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrapeInterval }}
      evaluation_interval: {{ .Values.config.evaluationInterval }}

    {{- if .Values.alerting.enabled }}
    alerting:
      alertmanagers:
      {{- toYaml .Values.alerting.alertmanagers | nindent 6 }}
    {{- end }}

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      {{- range .Values.config.scrapeConfigs }}
      - job_name: '{{ .job_name }}'
        metrics_path: {{ .metrics_path }}
        {{- if .scheme }}
        scheme: {{ .scheme }}
        {{- end }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
        {{- toYaml .kubernetes_sd_configs | nindent 8 }}
        {{- end }}
        {{- if .tls_config }}
        tls_config:
        {{- toYaml .tls_config | nindent 10 }}
        {{- end }}
        {{- if .bearer_token_file }}
        bearer_token_file: {{ .bearer_token_file }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
        {{- toYaml .relabel_configs | nindent 8 }}
        {{- end }}
        {{- if .static_configs }}
        static_configs:
        {{- toYaml .static_configs | nindent 8 }}
        {{- end }}
      {{- end }}
