apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-rules
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  {{- range .Values.rules }}
  {{ .name }}.yml: |
    groups:
    - name: {{ .name }}
      rules:
      {{- toYaml .rules | nindent 6 }}
  {{- end }}