apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      {{- range .Values.datasources }}
      - name: {{ .name }}
        type: {{ .type }}
        url: {{ .url }}
        access: {{ .access }}
        isDefault: {{ .isDefault }}
      {{- end }}