kong:
  image: kong:3.9.0
  proxyPort: 8000
  adminPort: 8001
  proxySSLPort: 8443
  adminSSLPort: 8444

migrations:
  image: kong:3.9.0

postgresHost: "postgres"      # The name of your Postgres service
postgresUser: "kong"
postgresDB: "kong"
# KONG_PG_PASSWORD should be set via secret

service:
  type: ClusterIP
  port: 8000

secrets:
  KONG_PG_PASSWORD: ""

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: kong.local
      paths:
        - path: /
          pathType: Prefix
  tls: []