apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-service.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "admin-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-service.name" . }}
    spec:
      containers:
        - name: admin-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 18 }}
              {{- end }}
            {{- end }}
          volumeMounts:
            # other mounts if any
            - name: logs
              mountPath: /app/logs   # adjust if your app writes logs elsewhere
      volumes:
        # other volumes if any
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "admin-service.fullname" . }}-logs