apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-service.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "admin-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-service.name" . }}
    spec:
      containers:
        - name: admin-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-service-secrets
                  key: SECRET_KEY
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-service-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-service-secrets
                  key: KONG_PG_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-service-secrets
                  key: POSTGRES_PASSWORD