apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | quote }}
