replicaCount: 1

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 8Gi
    # Uncomment if using GPU nodes:
    gpu: 1

persistence:
  enabled: true
  size: 10Gi
  storageClass: microk8s-hostpath

service:
  type: LoadBalancer
  port: 11434
  ip: 192.168.9.180
