replicaCount: 1

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 8Gi
    # Uncomment if using GPU nodes:
    gpu: 1

persistentVolume:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP
  port: 11434
