apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: gpt
data:
  IMAGE_PULL_POLICY: "Always"
  LOG_PATH: "/app/logs"
  DATA_PATH: "/app/data"

  # MongoDB
  MONGO_USERNAME: "mongoadmin"
  MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
  MONGO_DATABASE_NAME: "gptdb"

  # Kong/Postgres
  KONG_PG_USER: "kong"
  KONG_PG_DATABASE: "kong"

  # Microservices ports
  ADMIN_SERVICE_PORT: "8004"
  AUTH_SERVICE_PORT: "8002"
  CHAT_SERVICE_PORT: "8003"
  KONG_PROXY_PORT: "8000"
