image:
  repository: nelonissle7/gpt_admin
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8004

env:
  - name: DATABASE_URL
    value: "sqlite:///./auth.db"
  - name: AUTH_SERVICE_URL
    value: "http://kong-gateway:8000/auth"
  - name: KONG_ADMIN_URL
    value: "http://kong-gateway:8001/consumers"
  - name: OLLAMA_MODEL
    value: "llama3"
  # - name: OLLAMA_API_URL
  #   value: "http://ollama:11434"
  - name: MONGO_SERVICE_HOST
    value: "mongo_db"
  - name: MONGO_SERVICE_PORT
    value: "27017"

secrets:
  SECRET_KEY: ""
  MONGO_INITDB_ROOT_PASSWORD: ""
  KONG_PG_PASSWORD: ""
  POSTGRES_PASSWORD: ""

logsPersistence:
  enabled: true
  size: 1Gi