image:
  repository: nelonissle7/gpt_admin
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8004

env:
  - name: AUTH_SERVICE_URL
    value: "http://kong-gateway:8000/auth"
  - name: MONGO_INITDB_ROOT_USERNAME
    value: "mongoadmin"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: admin-service-secrets
        key: SECRET_KEY
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: admin-service-secrets
        key: MONGO_INITDB_ROOT_PASSWORD

secrets:
  SECRET_KEY: ""
  MONGO_INITDB_ROOT_PASSWORD: ""

logsPersistence:
  enabled: true
  size: 10Gi