apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki-config.yaml: |
    auth_enabled: {{ .Values.config.auth.enabled }}
    server:
      http_listen_port: {{ .Values.config.server.httpPort }}
      grpc_listen_port: {{ .Values.config.server.grpcPort }}
    ingester:
      wal:
        dir: /loki/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: {{ .Values.config.ingester.chunkIdlePeriod }}
      chunk_retain_period: {{ .Values.config.ingester.chunkRetainPeriod }}
    schema_config:
      configs:
        - from: "2020-10-15"
          store: boltdb-shipper
          object_store: {{ .Values.config.storage.type }}
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      filesystem:
        directory: /loki/chunks
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: {{ .Values.config.schema.retentionPeriod }}
      volume_enabled: true
      allow_structured_metadata: false
    compactor:
      working_directory: /loki/compactor
