apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-monitoring-config
  namespace: gpt-monitoring
data:
  IMAGE_PULL_POLICY: "IfNotPresent"
  LOG_PATH: "/app/logs"
  DATA_PATH: "/app/data"
  
  # Prometheus config
  PROMETHEUS_RETENTION: "15d"
  PROMETHEUS_SCRAPE_INTERVAL: "15s"
  
  # Grafana config
  GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-worldmap-panel"
  
  # ELK config
  ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  LOGSTASH_JAVA_OPTS: "-Xms512m -Xmx512m"
