apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama-tinyllama.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ollama-tinyllama.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ollama-tinyllama.name" . }}
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              {{- if .Values.resources.limits.gpu }}
              nvidia.com/gpu: {{ .Values.resources.limits.gpu }}
              {{- end }}
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
