apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  rules:
    - host: ollama.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  number: 11434
