apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
  selector:
    app: ollama
