version: "3.9"

services:
  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      # Use DB-less mode
      KONG_DATABASE: "off"
      # Load configuration from the file
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    networks:
      - gpt_backend_network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gpt_backend_network
    restart: always

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8002:8002"
    env_file:
      - ./auth_service/.env
    volumes:
      - ./auth_service:/app
    networks:
      - gpt_backend_network
    depends_on:
      - kong-gateway
    restart: always

#  chat_service:
#    build: ./chat_service
#    container_name: chat_service
#    ports:
#      - "8003:8003"
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8003
#    env_file:
#      - ./chat_service/.env
#    volums:
#      - ./chat_service:/app
#    networks:
#      - gpt_backend_network
#    depends_on:
#      - kong-gateway
#      - mongo_db
#    restart: always

volumes:
  mongo_data:

networks:
  gpt_backend_network:
    name: gpt_backend_network