apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth-service.name" . }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 18 }}
              {{- end }}
            {{- end }}
          volumeMounts:
            - name: sqlite-db
              mountPath: /app/data
            - name: logs
              mountPath: /app/logs  
      volumes:
        - name: sqlite-db
          persistentVolumeClaim:
            claimName: {{ include "auth-service.fullname" . }}-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "auth-service.fullname" . }}-logs