global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # — Kong metrics
  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ['kong-gateway:8001']

  # — Optionally scrape your services
  - job_name: auth_service
    metrics_path: /metrics
    static_configs:
      - targets: ['auth_service:8002']

  - job_name: chat_service
    metrics_path: /metrics
    static_configs:
      - targets: ['chat_service:8003']

  - job_name: admin_service
    metrics_path: /metrics
    static_configs:
      - targets: ['admin_service:8004']
