server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Kong logs
  - job_name: kong
    static_configs:
      - targets:
          - localhost
        labels:
          job: kong
          __path__: /var/log/kong/*.log

  # Individual microservice logs
  - job_name: microservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices
          __path__: /var/log/microservices/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            event: event
      - labels:
          service:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # Global logs from all services
  - job_name: global-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: global-logs
          __path__: /var/log/global/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            event: event
      - labels:
          service:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output
