global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # — API Gateway metrics
  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ['kong-gateway:8001']

  # — Application services
  - job_name: auth_service
    metrics_path: /metrics
    static_configs:
      - targets: ['auth_service:8002']

  - job_name: chat_service
    metrics_path: /metrics
    static_configs:
      - targets: ['chat_service:8003']

  - job_name: admin_service
    metrics_path: /metrics
    static_configs:
      - targets: ['admin_service:8004']

  # — Host metrics
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  # — Container metrics
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  # — Database metrics
  - job_name: mongodb-exporter
    static_configs:
      - targets: ['mongodb-exporter:9216']
    metrics_path: /metrics
      
  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']
