apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  type: NodePort
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: kong-proxy
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: kong-admin
      port: 8001
      targetPort: 8001
      nodePort: 30801
    - name: llm-proxy
      port: 11434
      targetPort: 11434
      nodePort: 31434
