replicaCount: 1

image:
  repository: nelonissle7/gpt_auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8002

env:
  - name: DATABASE_URL
    value: "sqlite:///app/data/auth.db"
  - name: ALGORITHM
    value: "HS256"
  - name: KONG_ADMIN_URL
    value: "http://kong-gateway:8001/consumers"
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: auth-service-secrets
        key: SECRET_KEY

resources: {}

secrets:
  SECRET_KEY: ""

persistence:
  enabled: true
  size: 1Gi
  storageClass: microk8s-hostpath

logsPersistence:
  enabled: true
  size: 10Gi