replicaCount: 1

image:
  repository: nelonissle7/gpt_auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8002

env:
  - name: DATABASE_URL
    value: "sqlite:///./auth.db"
  - name: ALGORITHM
    value: "HS256"
  - name: KONG_ADMIN_URL
    value: "http://kong-gateway:8001/consumers"
  - name: OLLAMA_MODEL
    value: "llama3"
  # - name: OLLAMA_API_URL
  #   value: "http://ollama:11434"
  - name: MONGO_SERVICE_HOST
    value: "mongo_db"
  - name: MONGO_SERVICE_PORT
    value: "27017"

resources: {}

secrets:
  SECRET_KEY: ""