apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: {{ .Values.config.serverPort }}
      grpc_listen_port: 0

    positions:
      filename: {{ .Values.config.positions.filename }}

    clients:
      - url: {{ .Values.loki.url }}

    scrape_configs:
      {{- range .Values.config.scrapeConfigs }}
      - job_name: {{ .job_name }}
        {{- if .pipeline_stages }}
        pipeline_stages:
          {{- toYaml .pipeline_stages | nindent 8 }}
        {{- end }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
          {{- toYaml .kubernetes_sd_configs | nindent 8 }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
          {{- toYaml .relabel_configs | nindent 8 }}
        {{- end }}
        {{- if .static_configs }}
        static_configs:
          {{- toYaml .static_configs | nindent 8 }}
        {{- end }}
      {{- end }}