{{- if .Values.useAsDaemonset }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "promtail.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "promtail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promtail.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "promtail.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
            - "-config.expand-env=true"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: {{ .Values.config.serverPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            {{- range $key, $value := .Values.volumes }}
            - name: {{ $key }}
              mountPath: {{ $value.mountPath }}
              {{- if $value.readOnly }}
              readOnly: {{ $value.readOnly }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ include "promtail.fullname" . }}-config
        {{- range $key, $value := .Values.volumes }}
        - name: {{ $key }}
          hostPath:
            path: {{ $value.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
      tolerations:
        - effect: NoSchedule
          operator: Exists
{{- end }}