apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: {{ .Values.kong.image }}
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: {{ .Values.postgresHost | quote }}
            - name: KONG_PG_USER
              value: {{ .Values.postgresUser | quote }}
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-secrets
                  key: KONG_PG_PASSWORD
            - name: KONG_PG_DATABASE
              value: {{ .Values.postgresDB | quote }}
          ports:
            - containerPort: {{ .Values.kong.proxyPort }}
            - containerPort: {{ .Values.kong.adminPort }}
            - containerPort: {{ .Values.kong.proxySSLPort }}
            - containerPort: {{ .Values.kong.adminSSLPort }}