apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kong.proxyPort }}
      targetPort: {{ .Values.kong.proxyPort }}
      name: proxy
    - port: {{ .Values.kong.adminPort }}
      targetPort: {{ .Values.kong.adminPort }}
      name: admin
    - port: {{ .Values.kong.proxySSLPort }}
      targetPort: {{ .Values.kong.proxySSLPort }}
      name: proxy-ssl
    - port: {{ .Values.kong.adminSSLPort }}
      targetPort: {{ .Values.kong.adminSSLPort }}
      name: admin-ssl
  selector:
    app: kong-gateway