apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          image: {{ .Values.migrations.image }}
          command: ["kong", "migrations", "bootstrap"]
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: {{ .Values.postgresHost | quote }}
            - name: KONG_PG_USER
              value: {{ .Values.postgresUser | quote }}
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-secrets
                  key: KONG_PG_PASSWORD
            - name: KONG_PG_DATABASE
              value: {{ .Values.postgresDB | quote }}
      restartPolicy: OnFailure