apiVersion: v1
kind: Service
metadata:
  name: kong-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: kong-database