apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chat-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chat-service.name" . }}
    spec:
      containers:
        - name: chat-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: SECRET_KEY
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: KONG_PG_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            # other mounts if any
            - name: logs
              mountPath: /app/logs   # adjust if your app writes logs elsewhere
      volumes:
        # other volumes if any
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "chat-service.fullname" . }}-logs