apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secrets
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | quote }}
  KONG_PG_PASSWORD: {{ .Values.secrets.KONG_PG_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}