# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Python Microservices CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build admin_service
        working-directory: ./gpt_backend/admin_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add your build commands here, e.g., python setup.py install

  test-admin:
    needs: build-admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and test admin_service
        working-directory: ./gpt_backend/admin_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest || true 

  build-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build auth_service
        working-directory: ./gpt_backend/auth_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add your build commands here, e.g., python setup.py install

  test-auth:
    needs: build-auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and test auth_service
        working-directory: ./gpt_backend/auth_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest  # || true

  build-chat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build chat_service
        working-directory: ./gpt_backend/chat_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add your build commands here, e.g., python setup.py install

  test-chat:
    needs: build-chat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and test chat_service
        working-directory: ./gpt_backend/chat_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest # || true

  deploy:
    needs: [test-admin, test-auth, test-chat]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push admin_service
        uses: docker/build-push-action@v6
        with:
          context: ./gpt_backend/admin_service
          file: ./gpt_backend/admin_service/Dockerfile
          push: true
          tags: nelonissle7/gpt_admin:latest

      - name: Build and push auth_service
        uses: docker/build-push-action@v6
        with:
          context: ./gpt_backend/auth_service
          file: ./gpt_backend/auth_service/Dockerfile
          push: true
          tags: nelonissle7/gpt_auth:latest

      - name: Build and push chat_service
        uses: docker/build-push-action@v6
        with:
          context: ./gpt_backend/chat_service
          file: ./gpt_backend/chat_service/Dockerfile
          push: true
          tags: nelonissle7/gpt_chat:latest